### ISSUE TITLE
ScatteringMatrix doesnt properly support empty scattering rows

### ISSUE THREAD

**Issue by youngmit** [youngmit/mocc#1]
The ScatteringMatrix class fails to properly represent scattering cross sections containing rows with no non-zero entries. While such a situation is unphysical, certain validation cases may require it.

**Comment by jipuwang** [comment]
The `ScatteringMatrix`constructor is now able to treat empty scattering rows now with the following behavior:
1. insert into `scat_`a zero-valued element
2. set the `ScatteringRow`data member such that `min_g`=`max_g`=row index and the `from`pointer pointing to a one-element array with value zero.

A corresponding unit test is added covering all methods of `ScatteringMatrix`and `ScatteringRow`, and a test of the corner case 1-group purely absorbing scattering matrix is also included. 

@youngmit
